// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class Edycja1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void edycja1() {
    driver.get("http://127.0.0.1:8000/");
    driver.manage().window().setSize(new Dimension(823, 691));
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(4)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(4)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(4)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("id_login")).click();
    driver.findElement(By.id("id_login")).sendKeys("akowalska");
    driver.findElement(By.id("id_password")).click();
    driver.findElement(By.id("id_password")).sendKeys("akowalska1234");
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.id("id_edit_button_2")).click();
    driver.findElement(By.id("id_first_name")).click();
    driver.findElement(By.id("id_first_name")).sendKeys("piotr");
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".ui-button-text")).click();
    driver.findElement(By.linkText("Logout")).click();
  }
}
